### ISSUE TITLE
Purge des comptes non cotisants après une durée fixée

### ISSUE THREAD

**Issue by TheoDurr** [ae-utbm/sith#544]
Lien des spécifications : [Google Docs](https://docs.google.com/document/d/1PBv-2ec1a2UXOThkHVDCos-FMB-8_WBmvNbNw0YoCAk/edit?usp=share_link)

### Objectif
Le trésorier général de l’Association des Étudiants s’est rendu compte qu’une somme élevée
d'argent “dormait” sur les comptes d’anciens cotisants inactifs depuis longtemps. L’objectif à
terme serait de récupérer cet argent après avoir les cotisant (ou l’ancien cotisant) concérnés
de leurs inactivités par mail. Sans réponse de leurs part et sous un certain délai, le compte
serait vidée et l’argent reviendrait à l’Association des Étudiants.

Quiconque souhaite contribuer à ce projet est bien évidemment le/la bienvenue.

### Pilotage
Cette demande étant assez conséquente, un projet spécifique lui est dédié : [projet Github](https://github.com/orgs/ae-utbm/projects/9)

Si un point essentiel selon vous est manquant dans le projet, merci de vous rapprocher de @Juknum ou @TheoDurr 

#### Avant de développer
Merci de vous rapprocher de @Juknum ou @TheoDurr afin de se répartir le travail efficacement, nous attribuons les différentes tâches.

#### Discuter
Un fil de discussion est aussi ouvert pour vous permettre de discuter de ce changement : [Discussion](https://github.com/orgs/ae-utbm/discussions/3)
Un post dans le forum du serveur aeDev est également à disposition : [forum-v3](https://discord.gg/VNaTUDZGvQ)

**Comment by imperosol** [comment]
Projet terminé.

Voire #861 #901 #913 et #940
