### ISSUE TITLE
Date d'envoi des mails dans l'utilisateur

### ISSUE THREAD

**Issue by TheoDurr** [ae-utbm/sith#550]
Il faut garder une trace des dates d'envoi des mails, pour qu'un membre du bureau habilité puisse y accéder en cas de réclamation.

**Comment by imperosol** [comment]
L'envoi des mails est gardé dans les fichiers de log, et les opérations de vidange sont stockées en db, avec leur date de mail d'avertissement et leur date d'exécution.
