### ISSUE TITLE
Ligne d'opération sur le compte

### ISSUE THREAD

**Issue by TheoDurr** [ae-utbm/sith#551]
Cette ligne doit pouvoir être configurable facilement.

### Détails de la ligne

- **Date** : _date de la purge_
- **Comptoir** : AE
- **Barman** : root
- **Montant** : _montant_
- **Etiquette** : Purge compte
- **Quantité** : 1
- **Méthode de paiement** : "Versé à l'association"

**Comment by imperosol** [comment]
A rajouter :
- montant
- client

**Comment by TheoDurr** [comment]
> - client

Cette ligne apparaît dans le compte client déjà, comme une transaction normale.
