### ISSUE TITLE
Exécution journalière du script

### ISSUE THREAD

**Issue by TheoDurr** [ae-utbm/sith#554]
Il faut créer la tâche CRON

**Comment by imperosol** [comment]
Faire tourner automatiquement implique que le trésorier ait le temps de faire son travail n'importe quand (voire qu'on ait un trésorier tout court). Faire ça à la main une fois tous les ans, à un moment où le trésorier est pleinement disponible et au courant qu'on va lancer l'opération, c'est bien.
