### ISSUE TITLE
Remontée des anomalies dans Sentry

### ISSUE THREAD

**Issue by TheoDurr** [ae-utbm/sith#557]

**Comment by Juknum** [comment]
Sentry "remarche" donc on doit pouvoir close cette issue ? à moins que c'est pas ce que tu voulais faire à la base 👀 

@TheoDurr

**Comment by Juknum** [comment]
Des news là dessus ? @TheoDurr

**Comment by TheoDurr** [comment]
Sentry est encore down, j'ai du l'éteindre.

**Comment by Juknum** [comment]
Okai, on pourrait faire comment pour le "réparer"?
